default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 }%>
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  timeout: 5000

development:
  <<: *default
  database: file_search_development

test:
  <<: *default
  database: file_search_test
